### ISSUE TITLE
pip installation fails - Not Found for url

### ISSUE THREAD

**Issue by mozdi** [ceeeeb/pibooth-nextcloud#1]
Hi all,

it seems like this plugin does not exist on https://pypi.org/simple/pibooth-nextcloud/ anymore.
Installation with pip fails:

```
$ pip3 install pibooth-nextcloud
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pibooth-nextcloud
**Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/pibooth-nextcloud/**

```

Is this plugin still working with pibooth?
Why is it not linked in the README section or on any other place where plugins are linked?

BR Mozdi

**Comment by ceeeeb** [comment]
Hi,

The plugin is being evaluated by the Pibooth team to be officially
integrated into the plugins.

Regards,
