### ISSUE TITLE
pip install fail :No module 'owncloud'

### ISSUE THREAD

**Issue by davtech42** [ceeeeb/pibooth-nextcloud#2]
Hello,
I try to install the plugin, but i've got an error message :

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pibooth-nextcloud
  Using cached https://files.pythonhosted.org/packages/b9/24/c54504975492920b0d7befa9ef079bc51310c3fbde0e5daa70b1d44f5bd0/pibooth_nextcloud-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-copnth8i/pibooth-nextcloud/setup.py", line 12, in <module>
        import pibooth_nextcloud as plugin
      File "/tmp/pip-install-copnth8i/pibooth-nextcloud/pibooth_nextcloud.py", line 12, in <module>
        import owncloud
    ModuleNotFoundError: No module named 'owncloud'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-copnth8i/pibooth-nextcloud/

**Comment by ceeeeb** [comment]
Hello, 

Can you try installing the pyocclient library

pip install pyocclient

**Comment by davtech42** [comment]
Hello ceeeeb,
I installed pyocclient, but i've got the same error message.

**Comment by ceeeeb** [comment]
Hello,

Can you sens me tour configuration

Os, php version,....

**Comment by davtech42** [comment]
Hello,
os : VERSION="10 (buster)"
PHP : version  8.2.12

**Comment by davtech42** [comment]
Hello ceeb,
if you want to connect to my raspberry using ssh, send me an email : davtech42@gmx.fr

**Comment by ceeeeb** [comment]
OK, that's it.

The pibooth_nextcloud component must not be installed with the "root" user,
but with the "pi" user.

pip3 install pibooth_nextcloud.

Now it should work !!

**Comment by davtech42** [comment]
Thank you.
Great plugin !!!
